// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: com.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "com";

/**
 * PipeMessage represents a generic message used in the Pipe communication system.
 *
 * Each message has:
 * - `type`: a string identifier to distinguish the kind of message.
 * - `payload`: a binary payload (usually encoded data).
 */
export interface PipeMessage {
  /** Identifier for the message type (e.g., "chat_message", "heartbeat"). */
  type: string;
  /** Serialized binary data corresponding to the message. */
  payload: Uint8Array;
}

function createBasePipeMessage(): PipeMessage {
  return { type: "", payload: new Uint8Array(0) };
}

export const PipeMessage: MessageFns<PipeMessage> = {
  encode(message: PipeMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PipeMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePipeMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PipeMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: PipeMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PipeMessage>, I>>(base?: I): PipeMessage {
    return PipeMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PipeMessage>, I>>(object: I): PipeMessage {
    const message = createBasePipeMessage();
    message.type = object.type ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

/**
 * PipeService provides a bidirectional streaming RPC method named `Communicate`.
 *
 * This enables both client and server to send and receive `PipeMessage` streams
 * in real-time, making it suitable for custom protocol implementations, messaging,
 * or RPC-over-stream scenarios.
 */
export type PipeServiceService = typeof PipeServiceService;
export const PipeServiceService = {
  communicate: {
    path: "/com.PipeService/Communicate",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: PipeMessage) => Buffer.from(PipeMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PipeMessage.decode(value),
    responseSerialize: (value: PipeMessage) => Buffer.from(PipeMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PipeMessage.decode(value),
  },
} as const;

export interface PipeServiceServer extends UntypedServiceImplementation {
  communicate: handleBidiStreamingCall<PipeMessage, PipeMessage>;
}

export interface PipeServiceClient extends Client {
  communicate(): ClientDuplexStream<PipeMessage, PipeMessage>;
  communicate(options: Partial<CallOptions>): ClientDuplexStream<PipeMessage, PipeMessage>;
  communicate(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<PipeMessage, PipeMessage>;
}

export const PipeServiceClient = makeGenericClientConstructor(PipeServiceService, "com.PipeService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PipeServiceClient;
  service: typeof PipeServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
